version: '2.1'

services:
  # Database instance
  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
    entrypoint:
      sh -c "
      echo 'CREATE DATABASE IF NOT EXISTS game; CREATE DATABASE IF NOT EXISTS profile;' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "

  # Auth instance
  auth:
    image: eu.gcr.io/withergate-215313/withergate-auth
    ports:
      - "9000:9000"
    environment:
      - "SPRING_PROFILES_ACTIVE=local"

  # Api instance
  api:
    image: eu.gcr.io/withergate-215313/withergate-api
    ports:
      - "8080:8080"
    restart: always
    environment:
      - "security.oauth2.resource.userInfoUri=http://auth:9000/user"
      - "game.datasource.jdbc-url=jdbc:mysql://database:3306/game?useSSL=false"
      - "profile.datasource.jdbc-url=jdbc:mysql://database:3306/profile?useSSL=false"
      - "SPRING_PROFILES_ACTIVE=local"
    depends_on:
      - database

  # Client instance
  client:
    image: eu.gcr.io/withergate-215313/withergate-client
    ports:
      - "3000:80"
    environment:
      - "API_URL=http://localhost:8080/"
      - "AUTH_URL=http://localhost:9000/"
      - "REDIRECT_URL=http://localhost:3000"
      - "CLIENT_ID=withergate-local"
      - "PROFILE=LOCAL"

