version: '3'

services:
  # Auth instance
  auth:
    image: eu.gcr.io/withergate-215313/withergate-auth
    ports:
      - "9000:9000"
    environment:
      - "SPRING_PROFILES_ACTIVE=local"

  # Api instance
  api:
    image: eu.gcr.io/withergate-215313/withergate-api
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
      - "security.oauth2.resource.userInfoUri=http://auth:9000/user"

  # Client instance
  client:
    image: eu.gcr.io/withergate-215313/withergate-client
    ports:
      - "3000:80"
    environment:
      - "API_URL=http://localhost:8080/"
      - "AUTH_URL=http://localhost:9000/"
      - "REDIRECT_URL=http://localhost:3000"
      - "CLIENT_ID=withergate-local"
